#!/usr/bin/env python
# -*- coding: utf-8 -*-
import sys

fi=open(sys.argv[1],"r")
fo=open(sys.argv[2],"w")
s=fi.read().decode('utf-8')
s=s.replace(u"а",u"А")
s=s.replace(u"б",u"Б")
s=s.replace(u"в",u"В")
s=s.replace(u"г",u"Г")
s=s.replace(u"д",u"Д")
s=s.replace(u"е",u"Е")
s=s.replace(u"ё",u"Ё")
s=s.replace(u"ж",u"Ж")
s=s.replace(u"з",u"З")
s=s.replace(u"и",u"И")
s=s.replace(u"й",u"Й")
s=s.replace(u"к",u"К")
s=s.replace(u"л",u"Л")
s=s.replace(u"м",u"М")
s=s.replace(u"н",u"Н")
s=s.replace(u"о",u"О")
s=s.replace(u"п",u"П")
s=s.replace(u"р",u"Р")
s=s.replace(u"с",u"С")
s=s.replace(u"т",u"Т")
s=s.replace(u"у",u"У")
s=s.replace(u"ф",u"Ф")
s=s.replace(u"х",u"Х")
s=s.replace(u"ц",u"Ц")
s=s.replace(u"ч",u"Ч")
s=s.replace(u"ш",u"Ш")
s=s.replace(u"щ",u"Щ")
s=s.replace(u"ы",u"Ы")
s=s.replace(u"ь",u"Ь")
s=s.replace(u"ъ",u"Ъ")
s=s.replace(u"э",u"Э")
s=s.replace(u"ю",u"Ю")
s=s.replace(u"я",u"Я")
fo.write(s.encode('utf-8'))
fi.close()
fo.close()

